[CmdletBinding()]
param(
    [string]$VocabularyDirectory,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $VocabularyDirectory) { $VocabularyDirectory = Join-Path $repoRoot 'vocabulary/entries' }
if (-not $OutputPath) { $OutputPath = Join-Path $repoRoot 'vocabulary/index.md' }

function Sort-Ordinal([object[]]$Values) {
    $items = [string[]]@($Values | ForEach-Object { [string]$_ })
    [Array]::Sort($items, [StringComparer]::Ordinal)
    return $items
}

function Sort-EntriesByTerm([object[]]$Entries) {
    $items = [object[]]@($Entries)
    if ($items.Count -le 1) { return $items }
    $selector = [Func[object,string]]{ param($item) [string]$item.term }
    return [Linq.Enumerable]::ToArray([Linq.Enumerable]::OrderBy($items, $selector, [StringComparer]::Ordinal))
}

function Display([string]$Value) {
    return (@($Value.Split('-') | Where-Object { $_.Length } |
        ForEach-Object { [char]::ToUpperInvariant($_[0]) + $_.Substring(1) }) -join ' ')
}

function Read-VocabularyEntries([string]$Directory) {
    $required = @('id','term','domain','definition','digital_relationship','best_use','technologies','node_refs','session_refs','related_terms','tags')
    $results = [Collections.Generic.List[object]]::new()
    $files = @(Get-ChildItem -LiteralPath $Directory -Filter '*.yaml' -File)
    foreach ($name in (Sort-Ordinal @($files | ForEach-Object { $_.Name }))) {
        $file = $files | Where-Object Name -eq $name | Select-Object -First 1
        $documents = [regex]::Split([IO.File]::ReadAllText($file.FullName), '(?m)^---\r?\n') | Where-Object { $_.Trim() }
        foreach ($document in $documents) {
            $values = [ordered]@{}
            foreach ($line in ($document.Trim() -split '\r?\n')) {
                if ($line -notmatch '^(?<key>[a-z_]+): (?<value>.+)$') { throw "Malformed vocabulary line in $($file.Name): $line" }
                $key = $Matches.key
                if ($key -notin $required -or $values.Contains($key)) { throw "Unsupported or duplicate vocabulary field '$key' in $($file.Name)" }
                try { $values[$key] = $Matches.value | ConvertFrom-Json -NoEnumerate } catch { throw "Vocabulary field '$key' must use a JSON-compatible YAML value in $($file.Name)" }
            }
            if (@($values.Keys).Count -ne $required.Count -or (@($required | Where-Object { -not $values.Contains($_) })).Count) {
                throw "Vocabulary entry in $($file.Name) does not contain exactly the required fields."
            }
            $results.Add([pscustomobject]$values)
        }
    }
    return $results
}

$entries = @(Read-VocabularyEntries $VocabularyDirectory)
if ($entries.Count -eq 0) { throw 'No canonical vocabulary entries found.' }
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# AudioMuse Vocabulary Index'); $lines.Add('')
$lines.Add('This file is generated by `tools/build-vocabulary-index.ps1`. Edit canonical entries in `vocabulary/entries/`, not this projection.')
$lines.Add(''); $lines.Add("Canonical vocabulary entries: $($entries.Count)")
$lines.Add(''); $lines.Add('## A-Z')
foreach ($entry in (Sort-EntriesByTerm $entries)) {
    $lines.Add(''); $lines.Add(('- **{0}** (`{1}`) — {2}' -f $entry.term, $entry.id, $entry.definition))
}
$lines.Add(''); $lines.Add('## By Domain')
foreach ($domain in (Sort-Ordinal @($entries.domain | Select-Object -Unique))) {
    $members = Sort-EntriesByTerm @($entries | Where-Object domain -ceq $domain)
    $lines.Add(''); $lines.Add(('### {0} — {1} terms' -f (Display $domain), $members.Count)); $lines.Add('')
    foreach ($entry in $members) { $lines.Add(('- `{0}` — {1}' -f $entry.id, $entry.term)) }
}
$lines.Add(''); $lines.Add('## By Session')
foreach ($sessionId in (Sort-Ordinal @($entries.session_refs | ForEach-Object { $_ } | Select-Object -Unique))) {
    $members = Sort-EntriesByTerm @($entries | Where-Object { $sessionId -cin $_.session_refs })
    $lines.Add(''); $lines.Add(('### `{0}` — {1} terms' -f $sessionId, $members.Count)); $lines.Add('')
    foreach ($entry in $members) { $lines.Add(('- `{0}` — {1}' -f $entry.id, $entry.term)) }
}
$lines.Add(''); $lines.Add('## By Canonical Node')
foreach ($nodeId in (Sort-Ordinal @($entries.node_refs | ForEach-Object { $_ } | Select-Object -Unique))) {
    $members = Sort-EntriesByTerm @($entries | Where-Object { $nodeId -cin $_.node_refs })
    $lines.Add(''); $lines.Add(('### `{0}` — {1} terms' -f $nodeId, $members.Count)); $lines.Add('')
    foreach ($entry in $members) { $lines.Add(('- `{0}` — {1}' -f $entry.id, $entry.term)) }
}
$content = ($lines -join "`n") + "`n"
$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $parent | Out-Null
[IO.File]::WriteAllText($OutputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Output "Generated vocabulary index from $($entries.Count) entries."
