[CmdletBinding()]
param([string]$RepositoryRoot, [string]$OutputDirectory)
$ErrorActionPreference = 'Stop'
if (-not $RepositoryRoot) { $RepositoryRoot = Split-Path -Parent $PSScriptRoot }
if (-not $OutputDirectory) { $OutputDirectory = Join-Path $RepositoryRoot 'indexes' }

function Sorted([object[]]$Values) { if($null -eq $Values){return @()}; $a=[string[]]@($Values|ForEach-Object{[string]$_}); [Array]::Sort($a,[StringComparer]::Ordinal); return $a }
function Scalar([string]$Text,[string]$Name) { $m=[regex]::Match($Text,"(?m)^${Name}: (?<v>[^\r\n]+)\r?$"); if(-not $m.Success){throw "Missing $Name"}; return $m.Groups['v'].Value.Trim('"') }
function List([string]$Text,[string]$Name) { if($Text -match "(?m)^${Name}: \[\]\r?$"){return @()}; $m=[regex]::Match($Text,"(?m)^${Name}:\r?\n(?<b>(?:  - [^\r\n]+\r?\n?)*)"); if(-not $m.Success){throw "Missing list $Name"}; return @([regex]::Matches($m.Groups['b'].Value,'(?m)^  - (?<v>[^\r\n]+)\r?$')|ForEach-Object{$_.Groups['v'].Value.Trim('"')}) }
function JsonRecords([string]$Directory) { $r=@(); foreach($name in (Sorted @(Get-ChildItem $Directory -Filter '*.yaml' -File|ForEach-Object Name))){$v=[ordered]@{}; foreach($line in [IO.File]::ReadAllLines((Join-Path $Directory $name))){if($line -notmatch '^(?<k>[a-z_]+): (?<v>.+)$'){throw "Malformed record: $name"}; $v[$Matches.k]=$Matches.v|ConvertFrom-Json -NoEnumerate}; $r += [pscustomobject]$v}; return @($r) }
function VocabularyRecords([string]$Directory) { $r=@(); foreach($name in (Sorted @(Get-ChildItem $Directory -Filter '*.yaml' -File|ForEach-Object Name))){foreach($doc in ([regex]::Split([IO.File]::ReadAllText((Join-Path $Directory $name)),'(?m)^---\r?\n')|Where-Object{$_.Trim()})){$v=[ordered]@{}; foreach($line in ($doc.Trim() -split '\r?\n')){if($line -notmatch '^(?<k>[a-z_]+): (?<v>.+)$'){throw "Malformed vocabulary: $name"};$v[$Matches.k]=$Matches.v|ConvertFrom-Json -NoEnumerate};$r += [pscustomobject]$v}};return @($r) }
function State([int]$Count) { if($Count -gt 0){'covered'}else{'unlinked'} }

$nodes=@(); foreach($file in @(Get-ChildItem (Join-Path $RepositoryRoot 'nodes') -Recurse -Filter '*.md'|Where-Object Name -ne 'README.md')){$text=[IO.File]::ReadAllText($file.FullName);$fm=[regex]::Match($text,'(?s)\A---\r?\n(?<y>.*?)\r?\n---').Groups['y'].Value;$edges=@();if($fm -notmatch '(?m)^relationships: \[\]\r?$'){$edges=@([regex]::Matches($fm,'(?m)^  - target: (?<target>[a-z0-9-]+)\r?\n    type: (?<type>[a-z0-9_]+)\r?$')|ForEach-Object{[pscustomobject]@{target=$_.Groups['target'].Value;type=$_.Groups['type'].Value}})};$nodes += [pscustomobject]@{id=Scalar $fm 'id';title=Scalar $fm 'title';domain=Scalar $fm 'domain';sessions=@(List $fm 'session_origin');sources=@(List $fm 'sources');practical=@(List $fm 'practical_applications');edges=$edges}}
$vocab=VocabularyRecords (Join-Path $RepositoryRoot 'vocabulary/entries');$experiments=JsonRecords (Join-Path $RepositoryRoot 'experiments/records');$runs=JsonRecords (Join-Path $RepositoryRoot 'experiment-runs/records')
$sourceText=[IO.File]::ReadAllText((Join-Path $RepositoryRoot 'sources/source-registry.yaml'));$sources=@([regex]::Matches($sourceText,'(?m)^  - id: (?<id>[a-z0-9-]+)\r?\n    type: (?<type>[a-z]+)')|ForEach-Object{[pscustomobject]@{id=$_.Groups['id'].Value;type=$_.Groups['type'].Value}});$sessions=@($sources|Where-Object type -ceq 'session')
$typeText=[IO.File]::ReadAllText((Join-Path $RepositoryRoot 'schemas/relationship-types.yaml'));$relationshipTypes=@([regex]::Matches($typeText,'(?m)^  - id: (?<id>[a-z0-9_]+)\r?$')|ForEach-Object{$_.Groups['id'].Value})
$nodeRows=@();$candidates=@()
foreach($id in (Sorted @($nodes.id))){$n=$nodes|Where-Object id -ceq $id|Select-Object -First 1;$in=@($nodes|ForEach-Object{$_.edges|Where-Object target -ceq $id});$v=@($vocab|Where-Object{$id -cin $_.node_refs});$e=@($experiments|Where-Object{$id -cin $_.node_refs});$completed=@($runs|Where-Object{$_.status -ceq 'completed' -and $_.experiment_id -cin $e.id});$types=@($n.edges.type)+@($in.type);$div=@($types|Select-Object -Unique).Count
  $experimentState=if($n.practical.Count -eq 0){'not_applicable'}elseif($e.Count -eq 0){'unlinked'}else{'covered'};$runState=if($n.practical.Count -eq 0){'not_applicable'}elseif($completed.Count){'covered'}elseif($e.Count){'partial'}else{'unlinked'}
  $nodeRows += [ordered]@{id=$id;domain=$n.domain;sessions=[ordered]@{state=State $n.sessions.Count;count=$n.sessions.Count;ids=@(Sorted $n.sessions)};sources=[ordered]@{state=State $n.sources.Count;count=$n.sources.Count;ids=@(Sorted $n.sources)};vocabulary=[ordered]@{state=State $v.Count;count=$v.Count;ids=@(Sorted $v.id)};experiments=[ordered]@{state=$experimentState;count=$e.Count;ids=@(Sorted $e.id)};completed_experiment_runs=[ordered]@{state=$runState;count=$completed.Count;ids=@(Sorted $completed.id)};inbound_relationships=$in.Count;outbound_relationships=$n.edges.Count;relationship_type_diversity=$div}
  if($n.sources.Count -eq 0){$candidates += [ordered]@{candidate_type='source_coverage';subject_type='node';subject_id=$id;evidence=[ordered]@{source_count=0};reason="The canonical $id node currently references no registered sources."}}
  if($n.sessions.Count -eq 0){$candidates += [ordered]@{candidate_type='session_coverage';subject_type='node';subject_id=$id;evidence=[ordered]@{session_count=0};reason="The canonical $id node currently maps to no chronological sessions."}}
  if($v.Count -eq 0){$candidates += [ordered]@{candidate_type='vocabulary_bridge';subject_type='node';subject_id=$id;evidence=[ordered]@{vocabulary_count=0};reason="The canonical $id node currently has no explicit vocabulary entry cross-reference."}}
  if($n.practical.Count -gt 0 -and $e.Count -eq 0){$candidates += [ordered]@{candidate_type='practical_evidence';subject_type='node';subject_id=$id;evidence=[ordered]@{practical_application_count=$n.practical.Count;experiment_count=0};reason="The canonical $id node declares practical applications but no experiment definition explicitly references it."}}
  if(($in.Count+$n.edges.Count) -le 1){$candidates += [ordered]@{candidate_type='relationship_coverage';subject_type='node';subject_id=$id;evidence=[ordered]@{inbound_count=$in.Count;outbound_count=$n.edges.Count;total_connection_count=($in.Count+$n.edges.Count)};reason="The canonical $id node currently participates in at most one typed relationship; this is a connectivity observation, not a defect."}}
}
$domains=@();$domainEnum=[regex]::Match([IO.File]::ReadAllText((Join-Path $RepositoryRoot 'schemas/node.schema.yaml')),'(?ms)^  domain:\r?\n.*?    enum:\r?\n(?<b>(?:      - [a-z0-9-]+\r?\n)*)').Groups['b'].Value;$domainIds=@([regex]::Matches($domainEnum,'(?m)^      - (?<id>[a-z0-9-]+)\r?$')|ForEach-Object{$_.Groups['id'].Value})
foreach($d in (Sorted $domainIds)){$dn=@($nodes|Where-Object domain -ceq $d);$dv=@($vocab|Where-Object domain -ceq $d);$de=@($experiments|Where-Object{@($_.node_refs|Where-Object{$_ -cin $dn.id}).Count -gt 0});$ds=@($dn.sources|ForEach-Object{$_}|Select-Object -Unique);$domains += [ordered]@{id=$d;node_count=$dn.Count;vocabulary_count=$dv.Count;experiment_count=$de.Count;source_count=$ds.Count};if($dn.Count -le 1){$candidates += [ordered]@{candidate_type='domain_representation';subject_type='domain';subject_id=$d;evidence=[ordered]@{node_count=$dn.Count};reason="The canonical domain $d currently contains at most one node; representation is sparse, not defective."}}}
$sessionRows=@();foreach($s in (Sorted $sessions.id)){$sessionRows += [ordered]@{id=$s;mapped_node_count=@($nodes|Where-Object{$s -cin $_.sessions}).Count;vocabulary_count=@($vocab|Where-Object{$s -cin $_.session_refs}).Count;experiment_count=@($experiments|Where-Object{$s -cin $_.session_refs}).Count}}
$candidateArray=[object[]]@($candidates);$selector=[Func[object,string]]{param($c) "$($c.candidate_type)|$($c.subject_type)|$($c.subject_id)"};$candidates=@([Linq.Enumerable]::ToArray([Linq.Enumerable]::OrderBy($candidateArray,$selector,[StringComparer]::Ordinal)))
$model=[ordered]@{schema='audiomuse-knowledge-coverage';version=1;authority='derived-read-only';overview=[ordered]@{node_count=$nodes.Count;relationship_count=@($nodes.edges|ForEach-Object{$_}).Count;relationship_type_count=$relationshipTypes.Count;source_count=$sources.Count;session_count=$sessions.Count;vocabulary_count=$vocab.Count;experiment_count=$experiments.Count;experiment_run_count=$runs.Count};nodes=$nodeRows;domains=$domains;sessions=$sessionRows;research_gap_candidates=$candidates}
New-Item -ItemType Directory -Path $OutputDirectory -Force|Out-Null;$json=($model|ConvertTo-Json -Depth 12).Replace("`r`n","`n");[IO.File]::WriteAllText((Join-Path $OutputDirectory 'knowledge-coverage.json'),$json.TrimEnd()+"`n",[Text.UTF8Encoding]::new($false))
$l=[Collections.Generic.List[string]]::new();$l.Add('# AudioMuse Knowledge Coverage');$l.Add('');$l.Add('> Generated, read-only, and non-authoritative. Rebuild with `tools/build-knowledge-coverage.ps1`; canonical repository content always wins.');$l.Add('');$l.Add('Coverage measures explicit repository relationships. It is not correctness, quality, truth, or universal completeness. A candidate is evidence for human review, not a knowledge defect.');$l.Add('');$l.Add('## Repository overview');$l.Add('');foreach($p in $model.overview.GetEnumerator()){$l.Add("- $($p.Key): $($p.Value)")};$l.Add('');$l.Add('## Node coverage');$l.Add('');$l.Add('| Node | Domain | Sessions | Sources | Vocabulary | Experiments | Completed runs | In | Out | Type diversity |');$l.Add('|---|---|---:|---:|---:|---:|---:|---:|---:|---:|');foreach($n in $nodeRows){$l.Add("| ``$($n.id)`` | $($n.domain) | $($n.sessions.count) | $($n.sources.count) | $($n.vocabulary.count) | $($n.experiments.count) | $($n.completed_experiment_runs.count) | $($n.inbound_relationships) | $($n.outbound_relationships) | $($n.relationship_type_diversity) |")};$l.Add('');$l.Add('## Domain coverage');$l.Add('');$l.Add('| Domain | Nodes | Vocabulary | Experiments | Sources |');$l.Add('|---|---:|---:|---:|---:|');foreach($d in $domains){$l.Add("| ``$($d.id)`` | $($d.node_count) | $($d.vocabulary_count) | $($d.experiment_count) | $($d.source_count) |")};$l.Add('');$l.Add('## Session coverage');$l.Add('');$l.Add('| Session | Nodes | Vocabulary | Experiments |');$l.Add('|---|---:|---:|---:|');foreach($s in $sessionRows){$l.Add("| ``$($s.id)`` | $($s.mapped_node_count) | $($s.vocabulary_count) | $($s.experiment_count) |")};$l.Add('');$l.Add('## Research-gap candidates');foreach($c in $candidates){$ev=@($c.evidence.GetEnumerator()|ForEach-Object{"$($_.Key)=$($_.Value)"}) -join ', ';$l.Add('');$l.Add("- **$($c.candidate_type)** — ``$($c.subject_type):$($c.subject_id)`` — evidence: $ev. $($c.reason)")};[IO.File]::WriteAllText((Join-Path $OutputDirectory 'knowledge-coverage.md'),($l -join "`n")+"`n",[Text.UTF8Encoding]::new($false));Write-Output "Generated knowledge coverage: $($nodes.Count) nodes, $($candidates.Count) candidates."
