[CmdletBinding()]
param(
    [string]$VocabularyDirectory,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $VocabularyDirectory) { $VocabularyDirectory = Join-Path $repoRoot 'vocabulary/entries' }
if (-not $OutputPath) { $OutputPath = Join-Path $repoRoot 'vocabulary/index.md' }

function Read-VocabularyEntries([string]$Directory) {
    $required = @('id','term','domain','definition','digital_relationship','best_use','technologies','node_refs','session_refs','related_terms','tags')
    $results = [Collections.Generic.List[object]]::new()
    foreach ($file in @(Get-ChildItem -LiteralPath $Directory -Filter '*.yaml' -File | Sort-Object Name)) {
        $documents = [regex]::Split([IO.File]::ReadAllText($file.FullName), '(?m)^---\r?\n') | Where-Object { $_.Trim() }
        foreach ($document in $documents) {
            $values = [ordered]@{}
            foreach ($line in ($document.Trim() -split '\r?\n')) {
                if ($line -notmatch '^(?<key>[a-z_]+): (?<value>.+)$') { throw "Malformed vocabulary line in $($file.Name): $line" }
                $key = $Matches.key
                if ($key -notin $required -or $values.Contains($key)) { throw "Unsupported or duplicate vocabulary field '$key' in $($file.Name)" }
                try { $values[$key] = $Matches.value | ConvertFrom-Json -NoEnumerate } catch { throw "Vocabulary field '$key' must use a JSON-compatible YAML value in $($file.Name)" }
            }
            if (@($values.Keys).Count -ne $required.Count -or (@($required | Where-Object { -not $values.Contains($_) })).Count) {
                throw "Vocabulary entry in $($file.Name) does not contain exactly the required fields."
            }
            $results.Add([pscustomobject]$values)
        }
    }
    return $results
}

function Sort-Ordinal([object[]]$Values) { @($Values | Sort-Object { $_.ToString() } -CaseSensitive) }
function Display([string]$Value) { (Get-Culture).TextInfo.ToTitleCase($Value.Replace('-', ' ')) }

$entries = @(Read-VocabularyEntries $VocabularyDirectory)
if ($entries.Count -eq 0) { throw 'No canonical vocabulary entries found.' }
$byId = @{}; foreach ($entry in $entries) { $byId[$entry.id] = $entry }
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# AudioMuse Vocabulary Index'); $lines.Add('')
$lines.Add('This file is generated by `tools/build-vocabulary-index.ps1`. Edit canonical entries in `vocabulary/entries/`, not this projection.')
$lines.Add(''); $lines.Add("Canonical vocabulary entries: $($entries.Count)")
$lines.Add(''); $lines.Add('## A-Z')
foreach ($entry in @($entries | Sort-Object term -CaseSensitive)) { $lines.Add(''); $lines.Add("- **$($entry.term)** (`$($entry.id)`) — $($entry.definition)") }
$lines.Add(''); $lines.Add('## By Domain')
foreach ($domain in (Sort-Ordinal @($entries.domain | Select-Object -Unique))) {
    $members = @($entries | Where-Object domain -eq $domain | Sort-Object term -CaseSensitive)
    $lines.Add(''); $lines.Add("### $(Display $domain) — $($members.Count) terms"); $lines.Add('')
    foreach ($entry in $members) { $lines.Add("- `$($entry.id)` — $($entry.term)") }
}
$lines.Add(''); $lines.Add('## By Session')
$sessionIds = Sort-Ordinal @($entries.session_refs | ForEach-Object { $_ } | Select-Object -Unique)
foreach ($sessionId in $sessionIds) {
    $members = @($entries | Where-Object { $sessionId -in $_.session_refs } | Sort-Object term -CaseSensitive)
    $lines.Add(''); $lines.Add("### `$sessionId` — $($members.Count) terms"); $lines.Add('')
    foreach ($entry in $members) { $lines.Add("- `$($entry.id)` — $($entry.term)") }
}
$lines.Add(''); $lines.Add('## By Canonical Node')
$nodeIds = Sort-Ordinal @($entries.node_refs | ForEach-Object { $_ } | Select-Object -Unique)
foreach ($nodeId in $nodeIds) {
    $members = @($entries | Where-Object { $nodeId -in $_.node_refs } | Sort-Object term -CaseSensitive)
    $lines.Add(''); $lines.Add("### `$nodeId` — $($members.Count) terms"); $lines.Add('')
    foreach ($entry in $members) { $lines.Add("- `$($entry.id)` — $($entry.term)") }
}
$content = ($lines -join "`n") + "`n"
$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $parent | Out-Null
[IO.File]::WriteAllText($OutputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Output "Generated vocabulary index from $($entries.Count) entries."
