[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=Split-Path -Parent $PSScriptRoot;$temp=Join-Path ([IO.Path]::GetTempPath()) ('audiomuse-coverage-tests-'+[guid]::NewGuid().ToString('N'));$fixture=Join-Path $temp 'repo';$passed=0
function Reset-Fixture {if(Test-Path $fixture){Remove-Item $fixture -Recurse -Force};New-Item $fixture -ItemType Directory|Out-Null;foreach($d in @('nodes','sources','schemas','vocabulary','experiments','experiment-runs')){Copy-Item (Join-Path $repoRoot $d) (Join-Path $fixture $d) -Recurse};New-Item (Join-Path $fixture 'indexes') -ItemType Directory|Out-Null;& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory (Join-Path $fixture 'indexes')|Out-Null}
function Replace([string]$Path,[string]$Old,[string]$New){$t=[IO.File]::ReadAllText($Path);if(-not$t.Contains($Old)){throw "Fixture text missing: $Old"};[IO.File]::WriteAllText($Path,$t.Replace($Old,$New),[Text.UTF8Encoding]::new($false))}
function Read-Model {return ([IO.File]::ReadAllText((Join-Path $fixture 'indexes/knowledge-coverage.json'))|ConvertFrom-Json)}
function Write-Model($Model){[IO.File]::WriteAllText((Join-Path $fixture 'indexes/knowledge-coverage.json'),((($Model|ConvertTo-Json -Depth 12) -split '\r?\n') -join "`n").TrimEnd()+"`n",[Text.UTF8Encoding]::new($false))}
function Candidate($Model,[string]$Type,[string]$Subject){return @($Model.research_gap_candidates|Where-Object{$_.candidate_type -ceq $Type -and $_.subject_id -ceq $Subject})[0]}
# Every failure class asserts the specific validator message so a test cannot pass
# by accidentally tripping the generic stale-output byte comparison instead.
function Expect-Failure([string]$Name,[string]$ExpectedMessage,[scriptblock]$Change){Reset-Fixture;&$Change;try{& (Join-Path $PSScriptRoot 'validate-knowledge-coverage.ps1') -RepositoryRoot $fixture *> $null;throw "Unexpected pass: $Name"}catch{$message=$_.Exception.Message;if($message -like 'Unexpected pass:*'){throw};if($message -notlike $ExpectedMessage){throw "Wrong failure for '$Name': expected like '$ExpectedMessage', got '$message'"};$script:passed++;Write-Output "PASS: $Name"}}
try{
 Expect-Failure 'missing node reference' '*Unresolved node reference: missing-node*' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') 'node_refs: ["frequency"' 'node_refs: ["missing-node"'}
 Expect-Failure 'missing source reference' '*Unresolved source reference: missing-source*' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') 'source_refs: ["session-01-what-is-sound"' 'source_refs: ["missing-source"'}
 Expect-Failure 'missing session reference' '*Unresolved session reference: missing-session*' {Replace (Join-Path $fixture 'vocabulary/entries/acoustic-foundations.yaml') 'session_refs: ["session-01-what-is-sound"]' 'session_refs: ["missing-session"]'}
 Expect-Failure 'invalid vocabulary reference' '*Unresolved vocabulary reference: missing-vocabulary*' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') 'vocabulary_refs: ["frequency"' 'vocabulary_refs: ["missing-vocabulary"'}
 Expect-Failure 'invalid experiment reference' '*Unresolved experiment reference: missing-experiment*' {Replace (Join-Path $fixture 'experiment-runs/records/near-frequency-beating-planned-a.yaml') 'experiment_id: "near-frequency-beating"' 'experiment_id: "missing-experiment"'}
 Expect-Failure 'canonical drift without rebuild' '*Coverage count disagrees with canonical facts*' {Replace (Join-Path $fixture 'vocabulary/entries/acoustic-interaction.yaml') 'node_refs: ["resonance"]' 'node_refs: ["sound"]'}
 Expect-Failure 'duplicate gap candidate' '*Duplicate gap candidate*' {$m=Read-Model;$m.research_gap_candidates=@($m.research_gap_candidates)+@($m.research_gap_candidates[0]);Write-Model $m}
 Expect-Failure 'malformed candidate type' '*Malformed candidate type*' {$m=Read-Model;$m.research_gap_candidates[0].candidate_type='knowledge_quality';Write-Model $m}
 Expect-Failure 'nonexistent candidate node subject' '*Candidate subject does not exist*' {$m=Read-Model;(Candidate $m 'practical_evidence' 'midi').subject_id='missing-node';Write-Model $m}
 Expect-Failure 'nonexistent candidate domain subject' '*Candidate subject does not exist*' {$m=Read-Model;(Candidate $m 'domain_representation' 'synthesis').subject_id='zz-missing-domain';Write-Model $m}
 Expect-Failure 'candidate evidence inconsistent with canonical facts' '*Candidate evidence inconsistent with canonical facts*' {$m=Read-Model;(Candidate $m 'vocabulary_bridge' 'midi').evidence.vocabulary_count=1;Write-Model $m}
 Expect-Failure 'unsupported research-gap candidate' '*not supported by canonical facts*' {$m=Read-Model;$extra=(Candidate $m 'vocabulary_bridge' 'synthesis').PSObject.Copy();$extra.subject_id='timbre';$m.research_gap_candidates=@($m.research_gap_candidates)+@($extra);Write-Model $m}
 Expect-Failure 'missing research-gap candidate' '*Missing research-gap candidate*' {$m=Read-Model;$m.research_gap_candidates=@($m.research_gap_candidates|Where-Object{$_.candidate_type -cne 'vocabulary_bridge' -or $_.subject_id -cne 'midi'});Write-Model $m}
 Expect-Failure 'broken generated candidate ordering' '*ordering is not deterministic*' {$m=Read-Model;$c=@($m.research_gap_candidates);$last=$c.Count-1;$swap=$c[$last];$c[$last]=$c[$last-1];$c[$last-1]=$swap;$m.research_gap_candidates=$c;Write-Model $m}
 Expect-Failure 'impossible coverage state' '*Impossible coverage state*' {$m=Read-Model;$m.nodes[0].sessions.state='good';Write-Model $m}
 Expect-Failure 'coverage id list disagrees with its own count' '*id list disagrees with its own count*' {$m=Read-Model;$row=@($m.nodes|Where-Object id -ceq 'midi')[0];$row.vocabulary.ids=@('');Write-Model $m}
 Expect-Failure 'coverage id list disagrees with canonical facts' '*id list disagrees with canonical facts*' {$m=Read-Model;$row=@($m.nodes|Where-Object id -ceq 'resonance')[0];$row.sources.ids=@('session-01-what-is-sound','session-02-what-is-music','session-02-what-is-music');Write-Model $m}
 Expect-Failure 'node coverage count disagrees with canonical facts' '*Coverage count disagrees with canonical facts*' {$m=Read-Model;$row=@($m.nodes|Where-Object id -ceq 'resonance')[0];$row.sources.count=99;Write-Model $m}
 Expect-Failure 'node coverage state disagrees with canonical facts' '*Coverage state disagrees with canonical facts*' {$m=Read-Model;$row=@($m.nodes|Where-Object id -ceq 'resonance')[0];$row.completed_experiment_runs.state='covered';Write-Model $m}
 Expect-Failure 'generated coverage node row count mismatch' '*node row count mismatch*' {$m=Read-Model;$m.nodes=@($m.nodes|Where-Object id -cne 'midi');Write-Model $m}
 Expect-Failure 'domain coverage disagrees with canonical facts' '*Coverage domain node_count disagrees with canonical facts*' {$m=Read-Model;@($m.domains|Where-Object id -ceq 'acoustics')[0].node_count=99;Write-Model $m}
 Expect-Failure 'session coverage disagrees with canonical facts' '*Coverage session mapped_node_count disagrees with canonical facts*' {$m=Read-Model;@($m.sessions|Where-Object id -ceq 'session-01-what-is-sound')[0].mapped_node_count=99;Write-Model $m}
 Expect-Failure 'generated coverage count mismatch' '*Generated coverage count mismatch*' {$m=Read-Model;$m.overview.node_count=999;Write-Model $m}
 Expect-Failure 'stale generated index' '*Generated coverage index is stale*' {[IO.File]::AppendAllText((Join-Path $fixture 'indexes/knowledge-coverage.md'),"stale`n",[Text.UTF8Encoding]::new($false))}
 Reset-Fixture;$a=Join-Path $temp 'a';$b=Join-Path $temp 'b';& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory $a|Out-Null;& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory $b|Out-Null;foreach($n in @('knowledge-coverage.md','knowledge-coverage.json')){if([Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $a $n)))-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $b $n)))){throw "Deterministic rebuild mismatch: $n"}};$passed++;Write-Output 'PASS: deterministic rebuild mismatch detection'
 foreach($n in @('knowledge-coverage.md','knowledge-coverage.json')){if(@([IO.File]::ReadAllBytes((Join-Path $a $n))|Where-Object{$_ -eq 13}).Count -ne 0){throw "Generated output contains carriage returns: $n"}};$passed++;Write-Output 'PASS: generated output is line-ending stable across platforms'
 foreach($row in (Read-Model).nodes){foreach($d in @('sessions','sources','vocabulary','experiments','completed_experiment_runs')){$ids=@($row.$d.ids|ForEach-Object{[string]$_});if($ids.Count -ne [int]$row.$d.count -or @($ids|Where-Object{-not $_}).Count -gt 0){throw "Generated id list is inconsistent: $($row.id) $d"}}};$passed++;Write-Output 'PASS: generated id lists carry no phantom identifiers'
 Write-Output "knowledge_coverage_tests_passed: $passed"
}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force}}
