[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=Split-Path -Parent $PSScriptRoot;$temp=Join-Path ([IO.Path]::GetTempPath()) ('audiomuse-coverage-tests-'+[guid]::NewGuid().ToString('N'));$fixture=Join-Path $temp 'repo';$passed=0
function Reset-Fixture {if(Test-Path $fixture){Remove-Item $fixture -Recurse -Force};New-Item $fixture -ItemType Directory|Out-Null;foreach($d in @('nodes','sources','schemas','vocabulary','experiments','experiment-runs')){Copy-Item (Join-Path $repoRoot $d) (Join-Path $fixture $d) -Recurse};New-Item (Join-Path $fixture 'indexes') -ItemType Directory|Out-Null;& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory (Join-Path $fixture 'indexes')|Out-Null}
function Replace([string]$Path,[string]$Old,[string]$New){$t=[IO.File]::ReadAllText($Path);if(-not$t.Contains($Old)){throw "Fixture text missing: $Old"};[IO.File]::WriteAllText($Path,$t.Replace($Old,$New),[Text.UTF8Encoding]::new($false))}
function Expect-Failure([string]$Name,[scriptblock]$Change){Reset-Fixture;&$Change;try{& (Join-Path $PSScriptRoot 'validate-knowledge-coverage.ps1') -RepositoryRoot $fixture *> $null;throw "Unexpected pass: $Name"}catch{if($_.Exception.Message-like'Unexpected pass:*'){throw};$script:passed++;Write-Output "PASS: $Name"}}
try{
 Expect-Failure 'missing node reference' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') '"frequency", "phase"' '"missing-node", "phase"'}
 Expect-Failure 'missing source reference' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') '"session-01-what-is-sound", "session-02-what-is-music"' '"missing-source", "session-02-what-is-music"'}
 Expect-Failure 'missing session reference' {Replace (Join-Path $fixture 'vocabulary/entries/acoustic-foundations.yaml') 'session_refs: ["session-01-what-is-sound"]' 'session_refs: ["missing-session"]'}
 Expect-Failure 'invalid vocabulary reference' {Replace (Join-Path $fixture 'experiments/records/near-frequency-beating.yaml') '"frequency", "phase", "waveform"' '"missing-vocabulary", "phase", "waveform"'}
 Expect-Failure 'invalid experiment reference' {Replace (Join-Path $fixture 'experiment-runs/records/near-frequency-beating-planned-a.yaml') 'experiment_id: "near-frequency-beating"' 'experiment_id: "missing-experiment"'}
 Expect-Failure 'duplicate gap candidate' {$p=Join-Path $fixture 'indexes/knowledge-coverage.json';$m=[IO.File]::ReadAllText($p)|ConvertFrom-Json;$m.research_gap_candidates=@($m.research_gap_candidates)+@($m.research_gap_candidates[0]);[IO.File]::WriteAllText($p,($m|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false))}
 Expect-Failure 'candidate evidence inconsistent with canonical facts' {$p=Join-Path $fixture 'indexes/knowledge-coverage.json';$m=[IO.File]::ReadAllText($p)|ConvertFrom-Json;$c=$m.research_gap_candidates|Where-Object candidate_type -ceq 'vocabulary_bridge'|Select-Object -First 1;$c.evidence.vocabulary_count=1;[IO.File]::WriteAllText($p,($m|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false))}
 Expect-Failure 'generated coverage count mismatch' {$p=Join-Path $fixture 'indexes/knowledge-coverage.json';$m=[IO.File]::ReadAllText($p)|ConvertFrom-Json;$m.overview.node_count=999;[IO.File]::WriteAllText($p,($m|ConvertTo-Json -Depth 12)+"`n",[Text.UTF8Encoding]::new($false))}
 Expect-Failure 'stale generated index' {$p=Join-Path $fixture 'indexes/knowledge-coverage.md';[IO.File]::AppendAllText($p,"stale`n",[Text.UTF8Encoding]::new($false))}
 Reset-Fixture;$a=Join-Path $temp 'a';$b=Join-Path $temp 'b';& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory $a|Out-Null;& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $fixture -OutputDirectory $b|Out-Null;foreach($n in @('knowledge-coverage.md','knowledge-coverage.json')){if([Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $a $n)))-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $b $n)))){throw "Deterministic rebuild mismatch: $n"}};$passed++;Write-Output 'PASS: deterministic rebuild mismatch detection'
 Write-Output "knowledge_coverage_tests_passed: $passed"
}finally{if(Test-Path $temp){Remove-Item $temp -Recurse -Force}}
