[CmdletBinding()]
param([string]$RepositoryRoot,[string]$ReportPath,[string]$JsonPath)
$ErrorActionPreference='Stop';if(-not $RepositoryRoot){$RepositoryRoot=Split-Path -Parent $PSScriptRoot};if(-not $ReportPath){$ReportPath=Join-Path $RepositoryRoot 'indexes/knowledge-coverage.md'};if(-not $JsonPath){$JsonPath=Join-Path $RepositoryRoot 'indexes/knowledge-coverage.json'}
function IdSet([string[]]$Ids){return ,[Collections.Generic.HashSet[string]]::new($Ids,[StringComparer]::Ordinal)}
function AssertRefs([string]$Kind,[object[]]$Refs,$Known){foreach($r in $Refs){if(-not $Known.Contains([string]$r)){throw "Unresolved $Kind reference: $r"}}}
function RecordFiles([string]$Dir){$r=@();foreach($f in Get-ChildItem $Dir -Filter '*.yaml' -File){$v=[ordered]@{};foreach($line in [IO.File]::ReadAllLines($f.FullName)){if($line -notmatch '^(?<k>[a-z_]+): (?<v>.+)$'){throw "Malformed record: $($f.Name)"};$v[$Matches.k]=$Matches.v|ConvertFrom-Json -NoEnumerate};$r += [pscustomobject]$v};return @($r)}
function VocabFiles([string]$Dir){$r=@();foreach($f in Get-ChildItem $Dir -Filter '*.yaml' -File){foreach($doc in ([regex]::Split([IO.File]::ReadAllText($f.FullName),'(?m)^---\r?\n')|Where-Object{$_.Trim()})){$v=[ordered]@{};foreach($line in ($doc.Trim() -split '\r?\n')){if($line -notmatch '^(?<k>[a-z_]+): (?<v>.+)$'){throw "Malformed vocabulary: $($f.Name)"};$v[$Matches.k]=$Matches.v|ConvertFrom-Json -NoEnumerate};$r += [pscustomobject]$v}};return @($r)}
if(-not(Test-Path $ReportPath)-or-not(Test-Path $JsonPath)){throw 'Missing generated knowledge coverage output.'};$model=[IO.File]::ReadAllText($JsonPath)|ConvertFrom-Json
if($model.schema -cne 'audiomuse-knowledge-coverage'-or$model.version-ne 1-or$model.authority-cne'derived-read-only'){throw 'Invalid knowledge coverage contract identity.'}
$nodeTexts=@(Get-ChildItem (Join-Path $RepositoryRoot 'nodes') -Recurse -Filter '*.md'|Where-Object Name -ne 'README.md'|ForEach-Object{[IO.File]::ReadAllText($_.FullName)});$nodeIds=@($nodeTexts|ForEach-Object{[regex]::Match($_,'(?m)^id: (?<v>[a-z0-9-]+)\r?$').Groups['v'].Value});$nodeSet=IdSet $nodeIds
$sourceText=[IO.File]::ReadAllText((Join-Path $RepositoryRoot 'sources/source-registry.yaml'));$sourceIds=@([regex]::Matches($sourceText,'(?m)^  - id: (?<v>[a-z0-9-]+)\r?$')|ForEach-Object{$_.Groups['v'].Value});$sourceSet=IdSet $sourceIds;$sessionIds=@([regex]::Matches($sourceText,'(?m)^  - id: (?<id>[a-z0-9-]+)\r?\n    type: session\r?$')|ForEach-Object{$_.Groups['id'].Value});$sessionSet=IdSet $sessionIds
$vocab=VocabFiles (Join-Path $RepositoryRoot 'vocabulary/entries');$vocabSet=IdSet @($vocab.id);$experiments=RecordFiles (Join-Path $RepositoryRoot 'experiments/records');$experimentSet=IdSet @($experiments.id);$runs=RecordFiles (Join-Path $RepositoryRoot 'experiment-runs/records');$runSet=IdSet @($runs.id)
foreach($t in $nodeTexts){AssertRefs 'node' @([regex]::Matches($t,'(?m)^  - target: (?<v>[a-z0-9-]+)\r?$')|ForEach-Object{$_.Groups['v'].Value}) $nodeSet;AssertRefs 'source' @([regex]::Match($t,'(?ms)^sources:\r?\n(?<b>(?:  - [^\r\n]+\r?\n?)*)').Groups['b'].Value -split '\r?\n'|Where-Object{$_}|ForEach-Object{$_.Substring(4)}) $sourceSet;AssertRefs 'session' @([regex]::Match($t,'(?ms)^session_origin:\r?\n(?<b>(?:  - [^\r\n]+\r?\n?)*)').Groups['b'].Value -split '\r?\n'|Where-Object{$_}|ForEach-Object{$_.Substring(4)}) $sessionSet}
foreach($v in $vocab){AssertRefs 'node' $v.node_refs $nodeSet;AssertRefs 'session' $v.session_refs $sessionSet;AssertRefs 'vocabulary' $v.related_terms $vocabSet}
foreach($e in $experiments){AssertRefs 'node' $e.node_refs $nodeSet;AssertRefs 'session' $e.session_refs $sessionSet;AssertRefs 'source' $e.source_refs $sourceSet;AssertRefs 'vocabulary' $e.vocabulary_refs $vocabSet;AssertRefs 'experiment' $e.related_experiments $experimentSet}
foreach($r in $runs){AssertRefs 'experiment' @($r.experiment_id) $experimentSet;AssertRefs 'source' $r.source_refs $sourceSet}
$edgeCount=@($nodeTexts|ForEach-Object{[regex]::Matches($_,'(?m)^  - target: [a-z0-9-]+\r?$').Count}|Measure-Object -Sum).Sum;$typeCount=@([regex]::Matches([IO.File]::ReadAllText((Join-Path $RepositoryRoot 'schemas/relationship-types.yaml')),'(?m)^  - id: [a-z0-9_]+\r?$')).Count
$expected=[ordered]@{node_count=$nodeIds.Count;relationship_count=$edgeCount;relationship_type_count=$typeCount;source_count=$sourceIds.Count;session_count=$sessionIds.Count;vocabulary_count=$vocab.Count;experiment_count=$experiments.Count;experiment_run_count=$runs.Count};foreach($p in $expected.GetEnumerator()){if([int]$model.overview.($p.Key)-ne$p.Value){throw "Generated coverage count mismatch: $($p.Key) expected $($p.Value), found $($model.overview.($p.Key))"}}
$validStates=@('covered','partial','unlinked','not_applicable');foreach($n in $model.nodes){if(-not$nodeSet.Contains($n.id)){throw "Coverage node does not exist: $($n.id)"};foreach($d in @('sessions','sources','vocabulary','experiments','completed_experiment_runs')){if($n.$d.state -cnotin $validStates){throw "Impossible coverage state: $($n.$d.state)"}}}
$keys=IdSet @();$previous='';foreach($c in $model.research_gap_candidates){$key="$($c.candidate_type)|$($c.subject_type)|$($c.subject_id)";if(-not$keys.Add($key)){throw "Duplicate gap candidate: $key"};if($previous-and[StringComparer]::Ordinal.Compare($previous,$key)-gt 0){throw 'Generated candidate ordering is not deterministic.'};$previous=$key;if($c.subject_type-ceq'node'-and-not$nodeSet.Contains($c.subject_id)){throw "Candidate subject does not exist: $key"};if($c.candidate_type-ceq'source_coverage'-and([int]$c.evidence.source_count-ne 0-or([int]($model.nodes|Where-Object id -ceq $c.subject_id).sources.count)-ne 0)){throw "Candidate evidence inconsistent with canonical facts: $key"};if($c.candidate_type-ceq'vocabulary_bridge'-and([int]$c.evidence.vocabulary_count-ne 0-or([int]($model.nodes|Where-Object id -ceq $c.subject_id).vocabulary.count)-ne 0)){throw "Candidate evidence inconsistent with canonical facts: $key"};if(-not$c.reason){throw "Candidate has no reason: $key"}}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('audiomuse-coverage-'+[guid]::NewGuid().ToString('N'));try{& (Join-Path $PSScriptRoot 'build-knowledge-coverage.ps1') -RepositoryRoot $RepositoryRoot -OutputDirectory $tmp|Out-Null;foreach($pair in @(@($ReportPath,(Join-Path $tmp 'knowledge-coverage.md')),@($JsonPath,(Join-Path $tmp 'knowledge-coverage.json')))){if([Convert]::ToBase64String([IO.File]::ReadAllBytes($pair[0]))-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($pair[1]))){throw "Generated coverage index is stale: $($pair[0])"}}}finally{if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force}}
Write-Output "coverage_nodes: $($expected.node_count)";Write-Output "coverage_relationships: $($expected.relationship_count)";Write-Output "coverage_candidates: $($model.research_gap_candidates.Count)";Write-Output 'knowledge_coverage_current: true'
